targets:
  $default:
    sources:
      exclude:
        - lib/**/*.g.dart
        - lib/**/*.freezed.dart
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
